---
- name: get JDK tarball (as RPM file)
  get_url:
    url:     "{{ jdk_rpm_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_download_path }}"
    validate_certs: false
  become: true

- name: install JDK via RPM file with yum
  yum:
    name: "{{ java_download_path }}/{{ jdk_rpm_file }}"
    state: present
  become: true
